### ISSUE TITLE
Unhandled session token refresh error

### ISSUE THREAD

**Issue by mklb** [realm/realm-js#1116]
I get a session refresh error after running an app for a view minutes in react native on iOS:
```
Unhandled session token refresh error: could not look up session at path /Users/XXXXXXX/Library/Developer/CoreSimulator/Devices/85A472DA-CBCB-416B-871B-50CA0DC03DFD/data/Containers/Data/Application/865345A1-6C84-4470-8055-0F9A65A86452/Documents/realm-object-server/dfeddc7733c15fb2b3108c217c1ce0db/realm%3A%2F%2Flocalhost%3A9080%2F%7E%2F__management
```

React native: 0.45
Realm: 1.8.3
Realm Obj. Server: 1.7.6
Simulator Device Version: iOS 10.3

**Comment by bmunkholm** [comment]
@mklb Can you post more details? Possibly ways for us to reproduce please?

**Comment by shenjiayu** [comment]
same here...
log from server:
`2017-07-05T07:31:38.160Z - info: sync-server: Sync Connection[40]: Session[6]: Received: REFRESH(signed_user_token='...YUf61E3dA6g8a/Q/d/OY9rH7v9oQ==')`

**Comment by fealebenpae** [comment]
Did you open a realm with sync that you then `close()`-d or left for the garbage collector?

**Comment by shenjiayu** [comment]
@fealebenpae 
I never called `close()`...

**Comment by fealebenpae** [comment]
Do you save it in a field somewhere, or just in a local variable?

**Comment by shenjiayu** [comment]
@fealebenpae 
```
let realm = null;
...
export default {
    ...,
    realm
};
```
I exported it for global use.

**Comment by fealebenpae** [comment]
Would it be possible to send your project to help@realm.io?

**Comment by shenjiayu** [comment]
@fealebenpae 
Yeah..Sure..

**Comment by shenjiayu** [comment]
@fealebenpae 
I sent the my project to the email, but I haven't gotten the reply yet..
Same error occurred when I called `Realm.open` to asynchronously open a realm and assign it the a variable like this
```
Realm.open({...}).then(realm => {
    this.realm = realm;
    ....
})
```

**Comment by shenjiayu** [comment]
@fealebenpae 
Once the realm is instantiated with
Realm.open({
    schema: [...],
    sync: {
    }
})
defined for local db,

**Comment by fealebenpae** [comment]
Hey @shenjiayu,

I’m sorry, I have been busy with other tasks and haven’t had the chance to look at your project yet. Thanks for the `path` hint - this helps me narrow down my search area.

**Comment by mklb** [comment]
this is how I use - and I think should use the library.

```javascript
Realm.Sync.User[action](Constants.dBUrl, username, password, (error, user) => {
  if (error) {
    // ....
  } else {
    this.realm = new Realm({
      schema: [..,..,..],
      schemaVersion: 5,
      sync: {
        user,
        url: XXXXXXX,
      },
    })

    this.realm.objects('XYYY').addListener((allObjects, changes) => {
      // ...
    })
  }
})
```

I could imagine that the error is thrown when I login with a not logged out user. Maybe because I often close and delete/reinstall the app without logging the user out.. 

However: I logged every user out before deleting the app today but I had this error every ~10 min... I planed to release my App this week but there is now way I can do it like that.

**Comment by fealebenpae** [comment]
@mklb is your error also `could not look up session at path`?

**Comment by mklb** [comment]
I opened the issue (first post). Yes ;) 
Same stack trace as @shenjiayu

**Comment by fealebenpae** [comment]
You could go to `node_modules/realm/lib/user-methods.js` and comment out this line: https://github.com/realm/realm-js/blob/master/lib/user-methods.js#L110 to disable the error. I still haven't been able to reproduce it and find out what's happening - it could be a false positive, but it could indicate a deeper issue. If you disable the error, does syncing still work - can you see changes reflected in the Realm Browser?

Also, in your app's stdout log, do you get a line that says `Closing Realm file` and the path you get in the error before you get the error?

**Comment by mklb** [comment]
I did not uncomment the code but I can tell you that syncing does work after clicking the dismiss button of the react native error popup view. So I guess your suggestion as a temporary workaround for a production app would be okay.. ¯\_(ツ)_/¯

**Comment by fealebenpae** [comment]
I made a complete and total stab-in-the-dark sort of fix. @mklb @shenjiayu could you please try it out?

[realm-1.9.0.tgz.zip](https://github.com/realm/realm-js/files/1141954/realm-1.9.0.tgz.zip)

(I had to zip it because GitHub doesn't like `.tgz`)

**Comment by mklb** [comment]
Did I do it right? I changed the package content of the `realm` folder in `/node_modules` with your package.

During the build phase it said: 
```
Downloading dependency: core 2.8.6
https://static.realm.io/downloads/core/realm-core-2.8.6.tar.xz
Downloading dependency: sync 1.10.5
https://static.realm.io/downloads/sync/realm-sync-cocoa-1.10.5.tar.xz
```
Does that mean your changes are overwritten because I did not change the version nr. in the `package.json` or are these just new dependencies?

Anyway, I´m testing it now and will edit this post in 15 min ;) Hopefully it will work. Thanks in advance for your effort and quick replies!

**Comment by fealebenpae** [comment]
> Does that mean your changes are overwritten

Nah, it’s only downloading Node.js binaries - React Native is separate from that.

I really hope this helps.

**Comment by mklb** [comment]
Edited my post. Sadly an error is thrown T_T

**Comment by fealebenpae** [comment]
How did you use the management realm? Did you log out any users?

**Comment by mklb** [comment]
Sorry for the late reply! I tried at again as follows:

1. Deleted the app from the virtual device
2. installed my app and registered as a new user to create fresh realms
3. ~10 min later the error occurs as above (`Could not look up session belonging to realm..`). just the `__management` realm does not refresh the session correctly

**Comment by mklb** [comment]
I will delete the realm server and install a fresh build. maybe the problem will be fixed this way..

Lets say I release an app with the monkey patch above ( https://github.com/realm/realm-js/issues/1116#issuecomment-314741116 ). We learned / saw that the users `__management` realms would not be synced after their first token expired.

In my case this would not be a problem since my users can´t change anything in the management realm anyway... The question is: is there any other drawback that I am missing or is it okay to just don`t care about the `__management` realm in my case?

**Comment by kneth** [comment]
@mklb Did the fresh installation solve the issue?

**Comment by kneth** [comment]
@mklb I close the issue. Don't hesitate to reopen or create a new.

**Comment by mklb** [comment]
sorry for the late reply. No it did not solve anything. this are my dependencies from `package.json` 

```
"realm": "^2.0.4",
"react": "16.0.0-alpha.12",
"react-native": "0.45",
```

**Comment by mklb** [comment]
My plan for finally releasing the app is to suppress as @fealebenpae suggested the error message. I will uncomment the line [118](https://github.com/realm/realm-js/blob/v2.0.4/lib/user-methods.js#L118) from the Realm version 2.0.4. Hope that helps some people out there as well..

Why version 2.0.4? Because the flow allows the app to fully function after that error is thrown / surppressed. 
This is not the case for version 2.0.12 btw! Line [103](https://github.com/realm/realm-js/blob/v2.0.12/lib/user-methods.js#L103) throws an undefined error for the session variable because the if statement from line [99](https://github.com/realm/realm-js/blob/v2.0.12/lib/user-methods.js#L99) does not catch that..

**Comment by kneth** [comment]
And you didn't add an error handler? It might help understand what the error is.

**Comment by mklb** [comment]
as far as I can see the version 2.0.4 just refreshes the token from the server so I dont need to do anything..?  ¯\_(ツ)_/¯

**Comment by kneth** [comment]
@mklb Do you have a proxy in front of your object server? 2.1.1 has a fix for that situation.

**Comment by mklb** [comment]
I do not think so. But I have no idea to be honest. The problem occurs with a local dev AND with a production object server on digital ocean. No idea why the problem is consistent through all the different SDKs and object server versions I have tried this year (see posts above)..

To recap: as far as I understand the SDK is unable to find the local token. I suppressed the error  message (SDK 2.0.4) so the app can continue to run. the sdk then just refreshes the token in ram (I guess) from the object server. maybe it even saves it locally on the device and is just unable to find it again.. I don´t know. It's also weird that I am the only one with this issue

I am testing my app in Testflight right now and the solution seems to work

**Comment by kneth** [comment]
@mklb If TestFlight can provide some insights, please share.

**Comment by mklb** [comment]
@kneth I invited you via your gmail address ;)

**Comment by kneth** [comment]
@mklb Thanks but I am an Android user 🤖 . @fealebenpae Can you help us?

**Comment by fealebenpae** [comment]
@mklb do you still get the `could not look up session at path` error for the `__management` realm?

**Comment by mklb** [comment]
@fealebenpae no, since I suppressed the error as you suggested -> https://github.com/realm/realm-js/issues/1116#issuecomment-349116464

**Comment by fealebenpae** [comment]
I think I understand. You correctly identified a bug with my original implementation where I never expected the `print_error` call to be recoverable, so the undefined error when accessing the session error handler wouldn't have been reached.

The relevant code in `user-methods.js` has been refactored and improved for this condition, I think, so perhaps the latest version should fix this problem for you altogether. Have you tried any newer version than 2.0.12?

**Comment by mklb** [comment]
I just installed / tested V.2.2.0 with my local ROS V.2.0.16 and received the same error after a few minutes of running the app.. frustrating :(

**Comment by kneth** [comment]
@mklb Thanks for the update.

@fealebenpae Does like ring a :bell*?

**Comment by fealebenpae** [comment]
I’m afraid not. I don’t understand how this happens in the first place.

**Comment by kneth** [comment]
@mklb Please try to upgrade (to 2.2.10). We have fixed a few bugs related to similar reports.

**Comment by bmunkholm** [comment]
Closing due to inactivity.
Please reopen when/if you can provide more details or the problem persist.

**Comment by lyseiha** [comment]
+1

**Comment by mklb** [comment]
The problem persisted. This is why I pulled the plug from the realm server for the production app.
