### ISSUE TITLE
Installing Realm Node.JS SDK professional edition - Error: Cannot find module '../compiled/linux-x64/node-v57/realm-node.node'

### ISSUE THREAD

**Issue by michael-mckenna** [realm/realm-js#1161]
## Goals

Trying to start a trial of the Realm Mobile Platform Professional Edition on my Linux server running CentOS 6.

## Expected Results

I followed the instructions precisely but once I try to run my code by doing `node index.js` I'm getting this error.

## Actual Results

Got this error:

module.js:487
    throw err;
    ^

Error: Cannot find module '../compiled/linux-x64/node-v57/realm-node.node'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mmckenna/TwilioSMSTest/node_modules/realm/lib/index.js:22:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

## Steps to Reproduce

Open a synchronized realm in NodeJS

## Code Sample

`    let appointmentRealm = new Realm({ 
            sync:  {
                user: adminUser, 
                url: "realm://***.com:9080/appointments"
            }, 
            schema: [AppointmentSchema] 
        });`

## Version of Realm and Tooling

- Realm JS SDK Version: Not sure how to check...it's the one emailed to me, the `realm-professional.tgz`
- Node or React Native: Node
- Client OS & Version: CentOS6
- Node Version: 8.2.1
- NPM Version: 5.3.0

**Comment by fealebenpae** [comment]
Hey @michael-mckenna, could you please try to downgrade your Node.js version to 6.x or 7.x? I think the tarball you were emailed might have been built before we added support for Node.js 8.

**Comment by michael-mckenna** [comment]
@fealebenpae Yep, that worked! Now it still works if I don't set the Realm.Sync.accessToken when I access a synchronized realm, however I do in fact need the realm-professional.tgz installed. What's the purpose of the access token then if my application still works without it?

**Comment by fealebenpae** [comment]
I believe the old `realm-professional.tgz` bundles came with a pre-baked token, but those were laborous to set up. With realm-js 1.8 and later you just `npm install realm` and then call `Realm.Sync.setAccessToken` to enable the sync features on Linux.

**Comment by michael-mckenna** [comment]
@fealebenpae Ok, so is this bundle outdated? Should I download realm-js 1.8 instead of using the tar if so? Additionally, will this pre-baked token expire in 14 days (the end of the free trial)?

**Comment by michael-mckenna** [comment]
@fealebenpae Ok so I uninstalled the `realm-professional.tgz` and instead ran `npm install --save realm` which installed realm-js 1.10. I made sure to set the access token with this time and I'm getting a `Error: Sync feature not available`. Sorry I'm just confused what package to use. It seems like I can only use the .tgz.

**Comment by ianpward** [comment]
@michael-mckenna You should be using the npm package - that is the latest version of realm-js. Can we see your full code, please?

**Comment by michael-mckenna** [comment]
@ianpward https://gist.github.com/michael-mckenna/b8142c5d39be7394c3df93d529dc8d92

**Comment by ianpward** [comment]
@michael-mckenna Unfortunately, realm-js does not support classes at this time. That is your issue - strange error message though. We should fix that. cc. @kneth

**Comment by michael-mckenna** [comment]
@ianpward Thanks for the response.

**Comment by michael-mckenna** [comment]
@ianpward Sorry, revisiting this issue again - what is the significance of your statement "realm-js does not support classes"? All I'm doing in the code is trying to open a realm instance inside a function using a given schema. 

If how I'm doing it is not correct, can you please let me know how I can change it to get it working? I'm still getting the error.

**Comment by ianpward** [comment]
This statement: https://gist.github.com/michael-mckenna/b8142c5d39be7394c3df93d529dc8d92#file-gistfile1-txt-L25

Uses classes - realm-js does not support it. Please remove that

**Comment by michael-mckenna** [comment]
@ianpward Okay, I did. I created a very basic file to test this (seen here https://gist.github.com/michael-mckenna/0059eaf5093eddba2e4fdc7fb25a96f6) and I am still getting the same error.

Please let me know if you still need more information.

**Comment by ianpward** [comment]
what is the output of: `node -v` and `npm -v` ?

Can you also send me your full code (including access token filled in) to help@realm.io and cc. ian.ward@realm.io

Thanks

**Comment by michael-mckenna** [comment]
@ianpward   Node V7.2.1, NPM 3.10.10. Thanks for staying in contact with me on this, I'll be sending the email shortly.

**Comment by michael-mckenna** [comment]
To anyone reading this - I had to receive an updated token and all started working.

**Comment by matbhz** [comment]
@michael-mckenna and Realm team is feature token problem still applicable? I'm on my 2nd day of the trial and actually requested a brand new trial token.

Using either of the Tokens fail to create a new `adatper`

```
/RealmTest/db_adatper.ts:28
		this.adapter = new Realm.Sync.Adapter(
		               ^

Error: Adapter feature not available.
```

Is that the case?

**Comment by ianpward** [comment]
hey @matbhz we have indeed fixed this - can you email me: ian.ward@realm.io and we will get you sorted
