### ISSUE TITLE
node does not exit if realm-js is imported

### ISSUE THREAD

**Issue by kvap** [realm/realm-js#1387]
## Goals

Use realm in a cli program.

## Expected Results

The program does its job and exits.

## Actual Results

Node does not exit.

## Steps to Reproduce

1. Import realm-js

## Code Sample

```javascript
require('realm');
console.log('hello');
```

It prints `hello` and hangs.

## Version of Realm and Tooling

- Realm JS SDK Version: the issue first appeared in `1.12.0`
- Node or React Native: Node 6.11.3
- Client OS & Version: macOS 10.12.6 and Debian 8

**Comment by kneth** [comment]
An ugly work-around is to call `process.exit()`.

**Comment by ashwinphatak** [comment]
I can reproduce this locally. `git bisect` between 1.11.1 and 1.12.0 throws up https://github.com/realm/realm-js/commit/e18f54594fa54aa33b2b81f9471835c980309f21 as the offending commit, which is strange because it's just the 'bump version' commit without any code changes.

During the `git bisect`, I've run the following to get a clean build each time: `git clean -xdf && git submodule update --init --recursive && npm install --build-from-source=realm`

**Comment by kneth** [comment]
Interesting. It must indicate that changes in `realm-js-private` is the trouble-maker. That means, I have to examine the changes there more closely.

**Comment by blagoev** [comment]
I tried to debug the issue and I suspect the problem is within the AdminRealmListener changes but couldn't narrow down the issue yet.

**Comment by bmunkholm** [comment]
If this is not quick to solve, I think we can postpone this. It seems a minor annoyance only when using in node.js with a script.

**Comment by stigi** [comment]
This also prevents jest from exiting after finishing all tests.
Now this is a major annoyance as it prevents us from running tests agains in memory realms (or importing realm at all in our tests).

I created a demo project to demonstrate the issue: https://github.com/stigi/realm-require-issue

**Comment by dehlen** [comment]
Any news on this one ? I can reproduce the described behavior with realm-js 2.3.1 and my jest tests won't terminate without adding the --forceExit hack.

**Comment by kneth** [comment]
Sorry, I haven't had time to prioritize it. In plain node scripts, calling `process.exit()` is fine but I can see the annoyance when you are testing.

**Comment by stigi** [comment]
@kneth Thanks for getting back to this issue.

I'm less worried about canceling async operations on my test stores than killing some script that works on production data.

**Comment by cyrusmg** [comment]
Any update on this issue ?

Building older versions of `realm` with Node v10 (LTS) crashes, building more recent version succeeds, but includes this bug which makes all realm tests fail (and using --forceExit hack for production code is really not the way to go). This means I am stuck with v8 until this issue is resolved.

**Comment by kneth** [comment]
@cyrusmg No updates to share - sorry. We are in the process to moving our code to a single repository (#2226) which I hope will help us to isolate the bug.

**Comment by kneth** [comment]
It looks like the issue has been resolved by a recent larger refactoring. At least, it doesn't happen to be when I use v2.28.0.

**Comment by ambertino** [comment]
Looks like still occurs in `10.4.2`

**Comment by emadridm** [comment]
it still happen at versión v10.5.0

**Comment by danielnieto** [comment]
still happens at version `10.6.0`

**Comment by liamjones** [comment]
I think we're also hitting this in Jest.

@kneth can we reopen this since it still appears to be happening? Or would you prefer we raise a new bug for it?

**Comment by tenebrius** [comment]
Also having this problem in 10.12.0

**Comment by moritzreiter** [comment]
My jest tests are still not exiting with realm 12.6.0.

I tried `realm.removeAllListeners()` and also `realm.close()`. Doesn't change a thing.

Only thing that works is running jest with `--force-exit`.
