### ISSUE TITLE
Android Error : can't debug in real phone

### ISSUE THREAD

**Issue by BINAIMENG** [realm/realm-js#1965]
## Goals

I want to debug in my real Android phone .

## Expected Results
I can see the state of my realm library on Chrome

## Actual Results
 

This is my error report:
Realm failed to connect to the embedded debug server inside the app. If attempting to use Chrome debugging from a device, ensure the device is reachable on the same network as this machine.
![1534407833 1](https://user-images.githubusercontent.com/19889708/44197582-9d770700-a171-11e8-8a9d-fc6762d62fda.jpg)

## Steps to Reproduce
Click on "Debug JS Remotely"on my phone.

## Version of Realm and Tooling

-"realm": "^2.14.2"
- "react-native": "0.55.4",
- android , windows

**Comment by kneth** [comment]
How do you connect your device to your computer? Did you enable port forwarding with `adb`?

**Comment by BINAIMENG** [comment]
Use data lines to link computers and cell phones, and then use "Debug JS Remotely".
Port forwarding is not enabled for `adb`
![qq_pic_merged_1534428334651](https://user-images.githubusercontent.com/19889708/44213628-b3e88700-a1a0-11e8-8a8b-0fdef7e3d942.jpg)
### My local IP is 192.168.3.166:8081, but Realm's IP is 192.168.5.101:8083. How can I get them all in the same IP environment?
@kneth

**Comment by kneth** [comment]
It sounds like your **internal** network is segregated into a number of subnetworks. It could be that traffic on ports 8081 and 8083 are not allowed between the subnetworks. But that is a bit of scope for Realm.

You can also connect your device using USB, set up port forwards using `adb` and connect to `127.0.0.1`.

**Comment by BINAIMENG** [comment]
Before using desktop computers, and then using laptops to open debug in WiFi connection mode. So the problem has been solved . thanks for help!

**Comment by thanhluantl2304** [comment]
![Realm_Emulator](https://user-images.githubusercontent.com/37209046/68464738-b3c02580-0243-11ea-9395-fb869a88de5e.PNG)

I debugged on real Android device ok but when i used Emulator to debug, i still faced this problem! Any one can help me about that?

**Comment by kneth** [comment]
@thanhluantl2304 It looks like the port forwarding isn't working as it should.
