### ISSUE TITLE
RealmObject cannot be called as a function - Only Android

### ISSUE THREAD

**Issue by saravanakumargn** [realm/realm-js#3876]
## Goals

When I try to use `objectForPrimaryKey` or `objects` it's working as expected in Both iOS and Android. like as below: 

``` javascript
// Working fine
const categoryData = realmRef.objects<CategorySchema>(CategorySchema).filtered(filterQuery).sorted('name'); 
```

``` javascript
// Create is not working in Android working fine in iOS
function saveCategory(values: ICategorySchema) {
  try {
    realmRef.write(() => {
      realmRef.create<CategorySchema>(CategorySchema, values, Realm.UpdateMode.Modified);
    });
    setIsCategoryFormModalVisible(false);
  } catch ({message}) {
    // eslint-disable-next-line no-console
    console.error(message);
  }
}
```

``` bash
 ERROR  RealmObject cannot be called as a function
```
## Expected Results

No issues while saving in iOS. Should as fine in Android like iOS.

## Actual Results

In Android it's throwing ` ERROR  RealmObject cannot be called as a function` on Create.

## Code Sample

``` javascript
import {UUIDType} from '@src/types';
import Realm from 'realm';
export interface ICategorySchema {
  _id: UUIDType;
  name: string;
  notes?: string;
  categoryType: number; // 0 - Income; 1 - Expenses
}

export class CategorySchema extends Realm.Object implements ICategorySchema {
  public _id: UUIDType;
  public name: string;
  public notes?: string;
  public categoryType: number;

  public static schema: Realm.ObjectSchema = {
    name       : 'Category',
    primaryKey : '_id',
    properties : {
      _id          : 'uuid',
      name         : 'string',
      categoryType : 'int',
      notes        : 'string?'
    }
  };
}
```

``` javascript
import Realm from 'realm';

import {
  CategorySchema,
} from './schemas';

// prettier-ignore
const realmRef = new Realm(
  {
    schema : [
      CategorySchema, 
    ],
    deleteRealmIfMigrationNeeded : __DEV__
  }
);

export default realmRef;

```
## Version of Realm and Tooling

- Realm JS SDK Version: "realm": "^10.6.1"
- Node or React Native: "react-native": "0.64.2",
- Client OS & Version: macOS Big Sur Version 11.5
- Which debugger for React Native: None

**Comment by fronck** [comment]
Hi @saravanakumargn.
Thanks for reporting this.  We'll look into the issue.

**Comment by takameyer** [comment]
@saravanakumargn I have created a fresh react-native app and implemented the source code you have provided.  This works for me without a problem in iOS and Android.  The only difference I could see is I am using Realm.BSON.UUID.  How are you implementing UUID?  Can you provide any other information?  Perhaps a sample repository that reproduces this exact issue?

**Comment by saravanakumargn** [comment]
This is not new code and It was working fine before `10.5.0` and previous versions(My code base was older, and the same implementation I had since v10). Now I changed all my `_id`s to 'uuid'. So, not able to revert older versions and test the same code.

@takameyer
Seems, Declaring schema using const is working fine. Using `public static schema` not working.

This is my UUID implementation.

``` javascript
const {UUID} = Realm.BSON;

export function getUUID(input?: string | Buffer | undefined): UUIDType {
  if (input) {
    try {
      return new UUID(input);
    } catch ({message}) {
      return new UUID();
    }
  }
  return new UUID();
}
```

**Comment by saravanakumargn** [comment]
FYI. This is not because of Reanimated v2 (I had removed and tested). Also, Able to list items using `realmRef.objects`.

![Screenshot_20210728-162046](https://user-images.githubusercontent.com/1115851/127310792-a5ba2ebe-69d9-46e5-b89c-0766e0468fdf.jpeg)

**Comment by takameyer** [comment]
@saravanakumargn Ah, are you calling `new` on your schema?  We do have some known issues involved with making a class extending "Realm.Object".  Can you try declaring your class without the extension and doing creates like so:
`realm.create<ObjectClass>('ObjectClass', value)`
This may be a workaround until we fix Class Based Models.

**Comment by saravanakumargn** [comment]
@takameyer 

After removing `extends Realm.Object` able to create the new object and not able to convert results to JSON(). So reverted back I will continue my development in ios.

```
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: item.toJSON is not a function. (In 'item.toJSON(index.toString(), cache)', 'item.toJSON' is undefined)
```

**Comment by takameyer** [comment]
@saravanakumargn the <T> added to any realm query or mutation will add `toJSON` (among other properties and functions of a realm object) to the given type.  What is the line of code providing `item` in this instance?

**Comment by saravanakumargn** [comment]
This is my list of objects.

```javascript
const [listData, setListData] = useState<IBatchSchema[]>();

const batchList: Realm.Results<BatchSchema & Realm.Object> = realmRef
  .objects<BatchSchema>(BatchSchema)
  .filtered(query);

setListData(batchesData.toJSON());
```

**Comment by takameyer** [comment]
@saravanakumargn try replacing `.objects<BatchSchema>(BatchSchema)` with `.objects<BatchSchema>('Batch')`.  If the name of the model is not `Batch`, then replace it with the correct schema name.

**Comment by saravanakumargn** [comment]
@takameyer 
This is working perfectly. Able to create new records using `.objects<BatchSchema>('Batch')`. But, still `toJSON()` not working

**Comment by takameyer** [comment]
@saravanakumargn I can reproduce this.  We will check into it and let you know as soon as we find something.

**Comment by fronck** [comment]
This may be related to  #3760.

**Comment by takameyer** [comment]
@saravanakumargn So I have dug into this deeper.  As I mentioned before, we have some known issues with classes that extend Realm.Object.  Unfortunately, in order to use toJSON, you do have to extend Realm.Object.  Extending Realm.Object causes the prototype of the class to contain the toJSON function, among other realm object properties and functions.  So I would continue to do so, but do not use the constructor.  There is a known issue here.  I would recommend defining a static function on your class which returns a normal js object that you can use to create new objects.  For example:
```
class Journal extends Realm.Object {
  id!: Realm.BSON.UDID;
  title!: string;
  content!: string;
  creationDate!: Date;

  static generate(title = 'New Entry', content = ''){
    return {
      id: new Realm.BSON.UDID(),
      title,
      content,
      creationDate: new Date(),
    };
  }

  static schema = {
    name: 'Journal',
    primaryKey: 'id',
    properties: {
      id: 'udid',
      title: 'string',
      content: 'string',
      creationDate: 'date',
      items: 'string[]',
    },
  };
}
//...
realm.write(() => {
    realm.create(Journal, Journal.generate('some title', 'some content'));
});
//...
const journals = realm.objects(Journal)
```

If all your classes follow this form, you should avoid the above problems.

**Comment by umarpazir11** [comment]
> @takameyer
> 
> After removing `extends Realm.Object` able to create the new object and not able to convert results to JSON(). So reverted back I will continue my development in ios.
> 
> ```
>  WARN  Possible Unhandled Promise Rejection (id: 0):
> TypeError: item.toJSON is not a function. (In 'item.toJSON(index.toString(), cache)', 'item.toJSON' is undefined)
> ```

I am facing exactly same issue.

**Comment by saravanakumargn** [comment]
@takameyer Do you have any idea/ETA about this fix in Android?

**Comment by takameyer** [comment]
@saravanakumargn I cannot say for sure when we will have these classes refactored.  Have you tried opening your Realm using the `schema` object instead of the class?  This should be a workaround to fix the `TypeError`.

**Comment by saravanakumargn** [comment]
@takameyer Still I am facing the error only in Android. I have modified my code as below. Please help me to fix this and check is anything I missed?.

```
Error: Constructor was not registered in the schema for this Realm
```

My Code:

``` ts
import Realm from 'realm';

import {
  SettingsSchema,
  ProfileSchema,
} from './schemas';

// prettier-ignore
const realmRef = new Realm(
  {
    schema : [
      SettingsSchema.schema,
      ProfileSchema.schema,
    ],
    deleteRealmIfMigrationNeeded : __DEV__
  }
);

export default realmRef;
```

``` ts
import Realm from 'realm';

import {UUIDType} from '@src/types';

export interface ISettingsSchema {
  languageCode: string;
  isRTL?: Boolean;
}

export class SettingsSchema extends Realm.Object implements ISettingsSchema {
  public _id: UUIDType;
  public languageCode: string;
  public isRTL?: Boolean;

  public static schema: Realm.ObjectSchema = {
    name       : 'Settings',
    primaryKey : '_id',
    properties : {
      _id          : 'uuid',
      languageCode : 'string',
      isRTL        : {
        type    : 'bool?',
        default : false
      }
    }
  };
}
```

Reading from `SettingsSchema`. Working fine in Android & iOS
``` ts
const settings = realmRef.objects<SettingsSchema>('Settings')[0];
```

``` ts
  function saveProfile(values: ISettingsSchema) {
    try {
      realmRef.write(() => {
        realmRef.create<SettingsSchema>('Settings', values, Realm.UpdateMode.Modified);
      });
      navigation.goBack();
    } catch ({message}) {
      // eslint-disable-next-line no-console
      console.error(message);
    }
  }
```
![Screenshot_20210831-124516](https://user-images.githubusercontent.com/1115851/131460221-d9b320e0-3c45-473d-a298-59289be3371b.jpeg)
![Screenshot_20210831-124507](https://user-images.githubusercontent.com/1115851/131460233-087eb620-d206-49a6-bb35-ac7c03cc87eb.jpeg)

**Comment by takameyer** [comment]
I think your non-optional class members should be declared using `!`.
For example:
```
  public _id!: UUIDType;
  public languageCode!: string;
 ```
 Other than that, the code looks correct and should be able to use `toJSON`.  What is your implementation of `toJSON`?  If you are querying realm using a string instead of the model class, than `toJSON` should be defined.

**Comment by saravanakumargn** [comment]
@takameyer

My issue got resolved. This is because of `react-native-animatable` v2. I didn't enable `enableHermes`, in my build.gradle still `enableHermes: false`.  After downgraded  `react-native-animatable` to v1, this undefined issue got resolved with your solution.

Thanks for your all support. really appreciate it.

Android getting an empty object, where iOS getting results of the first object. Because of empty object toJSON() is failing.

``` ts
function loadProfile() {
    const profileResults = realmRef.objects<ProfileSchema>('Profile').sorted('fullName');
    console.log(profileResults?.length) // 1
    console.log(profileResults?.[0]) // {}
    // setListData(profileResults.toJSON());
  }
```

**Comment by takameyer** [comment]
@saravanakumargn Thanks for following up on this.  Happy that you were able to get further along.  I will now close this issue

**Comment by tejasNix** [comment]
Still facing the same issue, with @realm/react and the hooks useRealm, useQuery.

![image](https://user-images.githubusercontent.com/92542008/167205469-df3baa80-f09d-4816-9433-048d4604ec4f.png)

**Comment by saravanakumargn** [comment]
@tejasNix without `@realm/react` is this working fine?

**Comment by theBeesAtWork** [comment]
@takameyer

The problem still persists on Android because of react-native-reanimatedV2
 
"react-native": "^0.70.0",
"realm": "^10.21.1",
"react-native-reanimated": "^2.10.0",
"@realm/react": "^0.3.2",

**Comment by takameyer** [comment]
@theBeesAtWork This should work with:
```
"realm": "11.0.0-rc.2"
```

**Comment by theBeesAtWork** [comment]
Thank you so much. You saved my life @takameyer. It works now with `"realm": "11.0.0-rc.2"`

**Comment by ismailsemihsenturk** [comment]
Still having the same error. 
I just used this template : `npx expo-cli init ReactRealmJSTemplateApp -t @realm/expo-template-js`
![photo_2022-09-24_02-45-10](https://user-images.githubusercontent.com/59211902/192070089-a7e16c89-c3e6-4d2d-b95f-2974556f23a6.jpg)

![image](https://user-images.githubusercontent.com/59211902/192070136-61ffa63a-96d1-4fdd-a2a5-5514f76cdce1.png)

**Comment by ismailsemihsenturk** [comment]
I updated my package.json file to be able to use `realm": "11.0.0-rc.2`
![image](https://user-images.githubusercontent.com/59211902/192072148-e0790264-738a-4bde-bd1d-9a6c60c151c5.png)

Now it's even worse 
![image](https://user-images.githubusercontent.com/59211902/192072119-b7f08a30-65eb-467d-bbe1-c90862b509e6.png)

First Error: android/app/build.gradle:
![image](https://user-images.githubusercontent.com/59211902/192072200-a69a1aaa-4fe5-4e7c-b157-3c7e8228aa7c.png)
![image](https://user-images.githubusercontent.com/59211902/192072330-230afc8e-f35f-4723-9484-a85efe021a68.png)

**Comment by kneth** [comment]
@ismailsemihsenturk Please check your dependencies against https://github.com/realm/realm-js/blob/master/COMPATIBILITY.md
