### ISSUE TITLE
Re-Authenticate Last-User during App restart while OFFLINE

### ISSUE THREAD

**Issue by reanzi** [realm/realm-js#4485]
### How frequently does the bug occur?

All the time

### Description

Restarting an application offline should Re-Authenticate the last-logged-in user.

But the application keep requiring internet connection to re-authenticate the last-user who was active before app restart.
though after that re-authentication, all activities proceed without connection just fine and syncing works fine when connected.

### Stacktrace & log output

```shell
No logs so far, just an empty white screen (simulator)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Just create an application with authentication enabled (I've used email and password), enable sync.

**// While you're online**
Login into the application
see everything is working (You see the application is working as normal)
Kill the application and restart it, it should re-authenticate the user just fine
Turn off internet connection

** // While OFFLINE **
restart the application
The app launches but never complete to main screens, stuck with empty white screen

### Version

realm: 10.13.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

windows 10, android Emulator

### Build environment

Which debugger for React Native: ..

**Comment by tomduncalf** [comment]
Hey @reanzi, you need to specify the behaviour you want in your Realm config. By default, opening a synced Realm will wait for the data to be synced before the `await Realm.open` promise returns. However, if you'd like to open the realm after a timeout when offline, you can do something like:

```js
const realmFileBehavior = {
  type: "downloadBeforeOpen",
  timeOut: 1000,
  timeOutBehavior: "openLocalRealm", // open the local realm if the download has not completed within 1000ms
};

const config = {
  schema: [Car], 
  sync: {
    user: app.currentUser, 
    partitionValue: "myPartition",
    existingRealmFileBehavior: realmFileBehavior, // <-- specify behaviour here
    newRealmFileBehavior: realmFileBehavior, // <-- and here
  },
};
```

You can read more in our docs: https://www.mongodb.com/docs/realm/sdk/react-native/examples/open-and-close-a-realm/#open-after-timeout-with-background-sync. Please note there's a typo in the code snippets there, `openLocal` should be `openLocalRealm` – I've reported this typo so it should be fixed soon.

Hope this helps – please feel free to reopen the issue with more details if you are still having problems.

**Comment by reanzi** [comment]
Sorry for late reply;
Thanks @tomduncalf, Sadly the problem still persist, I used your Behavior as you  suggested (like the docs in the link too) but still I'm having same problem. Earlier, I was using { type: _'openImmediately'} to force opening local Realm and sync in the background, had no lucky too.

when testing, please disconnect the computer from the network not only emulator. Using flight mode on the emulator alone does not _ prove, as somehow it manages to connect in the background using the computer's network I guess.

So the problem is not solved :sadly

**Comment by reanzi** [comment]
Thanks @takameyer , on my side no lucky so far 😢

**Comment by takameyer** [comment]
@reanzi I'll give this a quick investigation.  Can you provide the sync configuration that caused the issue (fileBehaviors)?

**Comment by reanzi** [comment]
Once authenticated while online it open local realm just fine even without
internet (no internet even on computer) but if you kill the app and open up
again, the application hangs with just a plain white screen, trying to
communicate with the cloud server( because at this stage if you reconnect
the internet, it loads fine)

I did try even to force using local with "immediately" but same issue

**Comment by reanzi** [comment]
Remember to simulate offline, try to disconnect even the computer you're
running emulator on, airplane mode on the emulator itself does prove the
reality as it somehow manages to connect (Please don't ask, I don't know
how :))

**Comment by reanzi** [comment]
@takameyer this is wat  I have so far
```
const realmFileBehavior = {
  type: "downloadBeforeOpen", // even 'openImmediately' did not work
  timeOut: 1000,
  timeOutBehavior: "openLocalRealm", // open the local realm if the download has not completed within 1000ms
};

const config = {
  schema: [Car], 
  sync: {
    user: app.currentUser, 
    partitionValue: "myPartition",
    existingRealmFileBehavior: realmFileBehavior, // <-- specify behaviour here
    newRealmFileBehavior: realmFileBehavior, // <-- and here
  },
};
```

**Comment by takameyer** [comment]
@reanzi nearly identical to mine.  What are you using to authenticate the user?  Email/Password?

**Comment by reanzi** [comment]
Yes, Email/Password plain simple

**Comment by takameyer** [comment]
@reanzi Unfortunately I am unable to reproduce this issue.  Perhaps you could make us a sample repo that shows the problem?

**Comment by reanzi** [comment]
😞 , Okay @takameyer I'll make a repo for this, because I've a project which depends on the proper functioning of such capability.
Thanks for the supports guys

**Comment by reanzi** [comment]
Hi guys, I'm back
[Sample Repo](https://github.com/reanzi/RealmOfflineDemo)

The repo is ready now, 
While testing, seems the intended behavior works when using local Realm only but not when using sync

**Comment by takameyer** [comment]
@reanzi thanks for providing that.  I'll take a look 👀

**Comment by takameyer** [comment]
@reanzi I ran your repo and setup the realm provider as follows:
```
//...
  <RealmProvider
          sync={{
            user,
            partitionValue: `${user.id}`,
            existingRealmFileBehavior: realmFileBehavior,
            newRealmFileBehavior: realmFileBehavior,
          }}>
          <Home />
        </RealmProvider>
// ...
const realmFileBehavior = {
  type: 'downloadBeforeOpen',
  timeOut: 1000,
  timeOutBehavior: 'openLocalRealm', // open the local realm if the download has not completed within 1000ms
};       
```
With this configuration, I was able to keep the user authenticated when restarting the application without internet connection.

**Comment by reanzi** [comment]
😄 thanks @takameyer ; 
Looks like passing those options needs to be done in the `RealmProvider` and not during `RealmContext` creation,
Because, same options works here

```
//...
  <RealmProvider
          sync={{
            user,
            partitionValue: `${user.id}`,
            existingRealmFileBehavior: realmFileBehavior,
            newRealmFileBehavior: realmFileBehavior,
          }}>
          <Home />
        </RealmProvider>
// ...

const realmFileBehavior = {
  type: 'downloadBeforeOpen',
  timeOut: 1000,
  timeOutBehavior: 'openLocalRealm', // open the local realm if the download has not completed within 1000ms
}; 
```

while here they doesn't 😮 🤔 

```
const OpenRealmBehaviorConfiguration = {
  type: 'openImmediately',
  timeOut: 1000,
  timeOutBehavior: 'openLocalRealm', // open the local realm if the download has not completed within 1000ms
};

export default createRealmContext({
  schema: [Task.schema],
  newRealmFileBehavior: OpenRealmBehaviorConfiguration,  // here
  existingRealmFileBehavior: OpenRealmBehaviorConfiguration, // here
});
```

> ### **Why is that, seems like one thing to be??????**

I had to only comment `here` and use your approach and 👍 everything works

You can close, this issue with your reply , Thanks everyone, @takameyer  and @tomduncalf  for the attention

**Comment by takameyer** [comment]
@reanzi You can do it in context creation as well, but you must set that on the `sync` property:
```
export default createRealmContext({
  schema: [Task.schema],
  sync: {
    newRealmFileBehavior: OpenRealmBehaviorConfiguration,
    existingRealmFileBehavior: OpenRealmBehaviorConfiguration,
  },
});
```
The above code will also work :)

**Comment by samevision** [comment]
Unfortunately it doesn't work for me either. In contrast to this thread I using flexible sync and I wrap the RealmProvider by AppProvider as well as UserProvider.

```js
const realmFileBehavior = {
    type: "downloadBeforeOpen",
    timeOut: 1000,
    timeOutBehavior: "openLocalRealm"
}

<AppProvider id="...">
    <UserProvider fallback={<SignIn />}>
        <RealmProvider sync={{
            flexible: true,
            existingRealmFileBehavior: realmFileBehavior,
            newRealmFileBehavior: realmFileBehavior
        }}>
           ...
        </RealmProvider>
    </UserProvider>
</AppProvider>
```

If I restart the app while being offline the SignIn component is displayed. So I assume that the UserProvider can't get the user. But I want the user to be logged in until he logs out regardless of internet connection. Is that possible?

**Comment by xzegga** [comment]
@samevision did you get that work? I am having the same issues trying to get it work with UserProvider without internet connection.
